# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb41c6bf2bb9440771a36de9c18db9a742a4d0e0952bac4e8cf4616775518040aeca070d044bc0af7ddf67b311c5da97c7769821cd66ea891408c9230f8e87d5

test:
  secret_key_base: bccf9fd76d1ef68ff37e9197927994e62b8898f4792ef569e68b98379314c13dcafc4a2b727aeee0f24b16b3f5ca9614fe9aa8504ea3a64ab5480523eb1cdb21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
